/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AproposRouteImport } from './routes/apropos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BouquetsRouteImport } from './routes/bouquets'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as EmploisRouteImport } from './routes/emplois'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as FinancementsRouteImport } from './routes/financements'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as PrincipesRouteImport } from './routes/principes'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as SmedlabRouteImport } from './routes/smedlab'
import { Route as ValeursRouteImport } from './routes/valeurs'
import { Route as VillesRouteImport } from './routes/villes'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AproposRoute = AproposRouteImport.update({
  id: '/apropos',
  path: '/apropos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BouquetsRoute = BouquetsRouteImport.update({
  id: '/bouquets',
  path: '/bouquets',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmploisRoute = EmploisRouteImport.update({
  id: '/emplois',
  path: '/emplois',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancementsRoute = FinancementsRouteImport.update({
  id: '/financements',
  path: '/financements',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipesRoute = PrincipesRouteImport.update({
  id: '/principes',
  path: '/principes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const SmedlabRoute = SmedlabRouteImport.update({
  id: '/smedlab',
  path: '/smedlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ValeursRoute = ValeursRouteImport.update({
  id: '/valeurs',
  path: '/valeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const VillesRoute = VillesRouteImport.update({
  id: '/villes',
  path: '/villes',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/blog': typeof BlogRouteWithChildren
  '/bouquets': typeof BouquetsRoute
  '/circuits': typeof CircuitsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRoute
  '/emplois': typeof EmploisRoute
  '/equipe': typeof EquipeRoute
  '/evenements': typeof EvenementsRoute
  '/financements': typeof FinancementsRoute
  '/formations': typeof FormationsRoute
  '/galerie': typeof GalerieRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/merci': typeof MerciRoute
  '/mission': typeof MissionRoute
  '/mon-compte': typeof MonCompteRoute
  '/partenaires': typeof PartenairesRoute
  '/principes': typeof PrincipesRoute
  '/reservation': typeof ReservationRoute
  '/smedlab': typeof SmedlabRoute
  '/valeurs': typeof ValeursRoute
  '/villes': typeof VillesRoute
  '/vision': typeof VisionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/blog': typeof BlogRouteWithChildren
  '/bouquets': typeof BouquetsRoute
  '/circuits': typeof CircuitsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRoute
  '/emplois': typeof EmploisRoute
  '/equipe': typeof EquipeRoute
  '/evenements': typeof EvenementsRoute
  '/financements': typeof FinancementsRoute
  '/formations': typeof FormationsRoute
  '/galerie': typeof GalerieRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/merci': typeof MerciRoute
  '/mission': typeof MissionRoute
  '/mon-compte': typeof MonCompteRoute
  '/partenaires': typeof PartenairesRoute
  '/principes': typeof PrincipesRoute
  '/reservation': typeof ReservationRoute
  '/smedlab': typeof SmedlabRoute
  '/valeurs': typeof ValeursRoute
  '/villes': typeof VillesRoute
  '/vision': typeof VisionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apropos': typeof AproposRoute
  '/blog': typeof BlogRouteWithChildren
  '/bouquets': typeof BouquetsRoute
  '/circuits': typeof CircuitsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRoute
  '/emplois': typeof EmploisRoute
  '/equipe': typeof EquipeRoute
  '/evenements': typeof EvenementsRoute
  '/financements': typeof FinancementsRoute
  '/formations': typeof FormationsRoute
  '/galerie': typeof GalerieRoute
  '/guides': typeof GuidesRoute
  '/login': typeof LoginRoute
  '/merci': typeof MerciRoute
  '/mission': typeof MissionRoute
  '/mon-compte': typeof MonCompteRoute
  '/partenaires': typeof PartenairesRoute
  '/principes': typeof PrincipesRoute
  '/reservation': typeof ReservationRoute
  '/smedlab': typeof SmedlabRoute
  '/valeurs': typeof ValeursRoute
  '/villes': typeof VillesRoute
  '/vision': typeof VisionRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apropos'
    | '/blog'
    | '/bouquets'
    | '/circuits'
    | '/contacts'
    | '/dashboard'
    | '/destinations'
    | '/emplois'
    | '/equipe'
    | '/evenements'
    | '/financements'
    | '/formations'
    | '/galerie'
    | '/guides'
    | '/login'
    | '/merci'
    | '/mission'
    | '/mon-compte'
    | '/partenaires'
    | '/principes'
    | '/reservation'
    | '/smedlab'
    | '/valeurs'
    | '/villes'
    | '/vision'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apropos'
    | '/blog'
    | '/bouquets'
    | '/circuits'
    | '/contacts'
    | '/dashboard'
    | '/destinations'
    | '/emplois'
    | '/equipe'
    | '/evenements'
    | '/financements'
    | '/formations'
    | '/galerie'
    | '/guides'
    | '/login'
    | '/merci'
    | '/mission'
    | '/mon-compte'
    | '/partenaires'
    | '/principes'
    | '/reservation'
    | '/smedlab'
    | '/valeurs'
    | '/villes'
    | '/vision'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/apropos'
    | '/blog'
    | '/bouquets'
    | '/circuits'
    | '/contacts'
    | '/dashboard'
    | '/destinations'
    | '/emplois'
    | '/equipe'
    | '/evenements'
    | '/financements'
    | '/formations'
    | '/galerie'
    | '/guides'
    | '/login'
    | '/merci'
    | '/mission'
    | '/mon-compte'
    | '/partenaires'
    | '/principes'
    | '/reservation'
    | '/smedlab'
    | '/valeurs'
    | '/villes'
    | '/vision'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AproposRoute: typeof AproposRoute
  BlogRoute: typeof BlogRouteWithChildren
  BouquetsRoute: typeof BouquetsRoute
  CircuitsRoute: typeof CircuitsRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  DestinationsRoute: typeof DestinationsRoute
  EmploisRoute: typeof EmploisRoute
  EquipeRoute: typeof EquipeRoute
  EvenementsRoute: typeof EvenementsRoute
  FinancementsRoute: typeof FinancementsRoute
  FormationsRoute: typeof FormationsRoute
  GalerieRoute: typeof GalerieRoute
  GuidesRoute: typeof GuidesRoute
  LoginRoute: typeof LoginRoute
  MerciRoute: typeof MerciRoute
  MissionRoute: typeof MissionRoute
  MonCompteRoute: typeof MonCompteRoute
  PartenairesRoute: typeof PartenairesRoute
  PrincipesRoute: typeof PrincipesRoute
  ReservationRoute: typeof ReservationRoute
  SmedlabRoute: typeof SmedlabRoute
  ValeursRoute: typeof ValeursRoute
  VillesRoute: typeof VillesRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apropos': {
      id: '/apropos'
      path: '/apropos'
      fullPath: '/apropos'
      preLoaderRoute: typeof AproposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouquets': {
      id: '/bouquets'
      path: '/bouquets'
      fullPath: '/bouquets'
      preLoaderRoute: typeof BouquetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emplois': {
      id: '/emplois'
      path: '/emplois'
      fullPath: '/emplois'
      preLoaderRoute: typeof EmploisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financements': {
      id: '/financements'
      path: '/financements'
      fullPath: '/financements'
      preLoaderRoute: typeof FinancementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principes': {
      id: '/principes'
      path: '/principes'
      fullPath: '/principes'
      preLoaderRoute: typeof PrincipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smedlab': {
      id: '/smedlab'
      path: '/smedlab'
      fullPath: '/smedlab'
      preLoaderRoute: typeof SmedlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valeurs': {
      id: '/valeurs'
      path: '/valeurs'
      fullPath: '/valeurs'
      preLoaderRoute: typeof ValeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villes': {
      id: '/villes'
      path: '/villes'
      fullPath: '/villes'
      preLoaderRoute: typeof VillesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AproposRoute: AproposRoute,
  BlogRoute: BlogRouteWithChildren,
  BouquetsRoute: BouquetsRoute,
  CircuitsRoute: CircuitsRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  DestinationsRoute: DestinationsRoute,
  EmploisRoute: EmploisRoute,
  EquipeRoute: EquipeRoute,
  EvenementsRoute: EvenementsRoute,
  FinancementsRoute: FinancementsRoute,
  FormationsRoute: FormationsRoute,
  GalerieRoute: GalerieRoute,
  GuidesRoute: GuidesRoute,
  LoginRoute: LoginRoute,
  MerciRoute: MerciRoute,
  MissionRoute: MissionRoute,
  MonCompteRoute: MonCompteRoute,
  PartenairesRoute: PartenairesRoute,
  PrincipesRoute: PrincipesRoute,
  ReservationRoute: ReservationRoute,
  SmedlabRoute: SmedlabRoute,
  ValeursRoute: ValeursRoute,
  VillesRoute: VillesRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
